-- SpecToRent Database Schema
-- PostgreSQL 14+
-- Generated from production database

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;

-- Users table
CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    company_name character varying(255),
    description character varying(1000),
    phone character varying(20),
    region character varying(255),
    avatar_url character varying(500)
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Rental items (equipment listings)
CREATE TABLE public.rental_items (
    id bigint NOT NULL,
    available_count integer,
    category character varying(255),
    daily_price numeric(12,2),
    description character varying(255),
    image_url character varying(255),
    location character varying(255),
    region character varying(255),
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255),
    owner_id bigint
);

ALTER TABLE public.rental_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rental_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Rental requests (orders)
CREATE TABLE public.rental_requests (
    id bigint NOT NULL,
    end_date date,
    start_date date,
    status character varying(255) NOT NULL,
    item_id bigint,
    renter_id bigint,
    quantity integer,
    address character varying(255)
);

ALTER TABLE public.rental_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rental_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Chat messages
CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    content character varying(2000) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    room_id character varying(255) NOT NULL,
    sender_id bigint
);

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Contract counter
CREATE TABLE public.contract_counter (
    id bigint NOT NULL,
    last_number bigint NOT NULL
);

ALTER TABLE public.contract_counter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_counter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary keys
ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rental_items ADD CONSTRAINT rental_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rental_requests ADD CONSTRAINT rental_requests_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.chat_messages ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.contract_counter ADD CONSTRAINT contract_counter_pkey PRIMARY KEY (id);

-- Unique constraints
ALTER TABLE ONLY public.users ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

-- Foreign keys
ALTER TABLE ONLY public.rental_items
    ADD CONSTRAINT fk6rvqo2905pkdn5ufvc01e6liq FOREIGN KEY (owner_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.rental_requests
    ADD CONSTRAINT fk4svh7p6bayw0hud1g59xdaf9i FOREIGN KEY (renter_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.rental_requests
    ADD CONSTRAINT fkgb31d3xgxecws7rg6ypo3969s FOREIGN KEY (item_id) REFERENCES public.rental_items(id);

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkgiqeap8ays4lf684x7m0r2729 FOREIGN KEY (sender_id) REFERENCES public.users(id);

-- Initial contract counter
INSERT INTO public.contract_counter (last_number) VALUES (0);
